defaultMarkdownHandler = "goldmark"

[goldmark]
[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[goldmark.parser.attribute]
block = true
title = true

[goldmark.renderer]
unsafe = true

[goldmark.extensions]
linkify = false

[highlight]
noClasses = false
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
hl_inline = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noHl = false
style = "monokai"
tabWidth = 2

[tableOfContents]
endLevel = 3
ordered = false
startLevel = 2